package GUI;

import dataBase.AsistenteDAO;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import lógica.Administrador;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 * Ventana para asignar una asistencia a una persona ya registrada.
 * @author Max Emmanuel Sierra Gómez
 * @version 1.0.0
 * Última fecha de actualización: 04/07/2016
 */
public class AsignarAsistencia extends javax.swing.JFrame {
    
    private AsistenteDAO asisDAO;
    private Administrador admin;

    /**
     * Creates new form AsignarAsistencia.
     */
    public AsignarAsistencia() {
        initComponents();
        this.asisDAO = new AsistenteDAO();
        admin = new Administrador();
        this.autocompletar();
        this.setDia();
    }

    /**
     * Método para volver autocompletable el combobox de los nombres de los asistentes
     */
    public void autocompletar(){
        this.cbx_nombreAsistente.removeAllItems();
        String linea = this.asisDAO.obtenerLista();
        String[] nombres = linea.split("\\|");
        this.cbx_nombreAsistente.setModel(new javax.swing.DefaultComboBoxModel(nombres));
        AutoCompleteDecorator.decorate(this.cbx_nombreAsistente);
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_asignarAsistencia = new javax.swing.JLabel();
        panel_asignarAsistencia = new javax.swing.JPanel();
        lbl_nombreAsistente = new javax.swing.JLabel();
        lbl_diaAsistencia = new javax.swing.JLabel();
        cbx_diasAsistencia = new javax.swing.JComboBox<>();
        cbx_nombreAsistente = new javax.swing.JComboBox<>();
        btn_asignarAsistencia = new javax.swing.JButton();
        btn_cancelarAsignarAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_asignarAsistencia.setFont(new java.awt.Font("Batang", 1, 36)); // NOI18N
        lbl_asignarAsistencia.setText("Asignar asistencia");

        panel_asignarAsistencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asistente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        lbl_nombreAsistente.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_nombreAsistente.setText("Nombre:");

        lbl_diaAsistencia.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_diaAsistencia.setText("Día de asistencia:");

        cbx_diasAsistencia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbx_diasAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lunes", "martes", "miercoles", "jueves", "viernes" }));

        cbx_nombreAsistente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout panel_asignarAsistenciaLayout = new javax.swing.GroupLayout(panel_asignarAsistencia);
        panel_asignarAsistencia.setLayout(panel_asignarAsistenciaLayout);
        panel_asignarAsistenciaLayout.setHorizontalGroup(
            panel_asignarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_asignarAsistenciaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_asignarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombreAsistente)
                    .addComponent(lbl_diaAsistencia))
                .addGap(33, 33, 33)
                .addGroup(panel_asignarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx_diasAsistencia, 0, 250, Short.MAX_VALUE)
                    .addComponent(cbx_nombreAsistente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panel_asignarAsistenciaLayout.setVerticalGroup(
            panel_asignarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_asignarAsistenciaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_asignarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreAsistente)
                    .addComponent(cbx_nombreAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panel_asignarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_diaAsistencia)
                    .addComponent(cbx_diasAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btn_asignarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/set2.png"))); // NOI18N
        btn_asignarAsistencia.setText("Asignar");
        btn_asignarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarAsistenciaActionPerformed(evt);
            }
        });

        btn_cancelarAsignarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        btn_cancelarAsignarAsistencia.setText("Cancelar");
        btn_cancelarAsignarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarAsignarAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lbl_asignarAsistencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(panel_asignarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btn_asignarAsistencia)
                        .addGap(26, 26, 26)
                        .addComponent(btn_cancelarAsignarAsistencia)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbl_asignarAsistencia)
                .addGap(18, 18, 18)
                .addComponent(panel_asignarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_asignarAsistencia)
                    .addComponent(btn_cancelarAsignarAsistencia))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarAsignarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarAsignarAsistenciaActionPerformed
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_btn_cancelarAsignarAsistenciaActionPerformed

    private void btn_asignarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarAsistenciaActionPerformed
        if(admin.actualizarAsistente((String) this.cbx_nombreAsistente.getSelectedItem(), (String) this.cbx_diasAsistencia.getSelectedItem())){
            JOptionPane.showMessageDialog(null,"Asistencia asignada exitosamente.");
        }else{
            JOptionPane.showMessageDialog(null,"Asistencia no asignada.");
        }
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_btn_asignarAsistenciaActionPerformed

    /**
     * Método para poner el día actual en el combo box.
     */
    private void setDia(){
        Calendar calendario = new GregorianCalendar();
        System.out.println(calendario.get(Calendar.DAY_OF_WEEK));
        this.cbx_diasAsistencia.setSelectedIndex(calendario.get(Calendar.DAY_OF_WEEK) - 2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asignarAsistencia;
    private javax.swing.JButton btn_cancelarAsignarAsistencia;
    private javax.swing.JComboBox<String> cbx_diasAsistencia;
    private javax.swing.JComboBox<String> cbx_nombreAsistente;
    private javax.swing.JLabel lbl_asignarAsistencia;
    private javax.swing.JLabel lbl_diaAsistencia;
    private javax.swing.JLabel lbl_nombreAsistente;
    private javax.swing.JPanel panel_asignarAsistencia;
    // End of variables declaration//GEN-END:variables
}